### ISSUE TITLE
Add documentation GHA

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/FDO-support#17]
Following the pattern used in the anax and mgmt-hub repos, implement a GHA to copy the docs in this repo's /docs folder to the appropriate path in the documentation repo (open-horizon.github.io) under /docs/???

@johnwalicki Do you have a preference for the path?  Do we match the pattern in mgmt-hub where the web path does not match the repo name?  /docs/fdo

Or do you prefer that they match?  /docs/FDO-support

**Comment by johnwalicki** [comment]
`/docs/fdo` is simpler.

You would start with the GHA over in the devops repo
https://github.com/open-horizon/devops/blob/master/.github/workflows/copy-docs.yml

**Comment by johnwalicki** [comment]
The CopyDocs GHA ran successfully and copied the docs/ files from this repo to the open-horizon.github.io repo.

Pages copied to https://github.com/open-horizon/open-horizon.github.io/tree/master/docs/fdo
