### ISSUE TITLE
Add front matter to the /docs .md files

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/FDO-support#21]
Other pages use front matter similar to this:

---

copyright:
years: 2022 - 2023
lastupdated: "2023-02-18"
layout: page
title: "FDO Installation"
description: "Detailed documentation on installing FDO support for new edge devices"

nav_order: 20
has_children: false
has_toc: false
---

**Comment by johnwalicki** [comment]
I added these technical references under the Administering section of the OH docs.  They will be a child and grandchild under this page:
https://open-horizon.github.io/docs/administering_index/

FWIW - We should add a link to these FDO docs in the index
https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/administering_index.html

**Comment by johnwalicki** [comment]
Before:
![image](https://user-images.githubusercontent.com/17571232/219902617-be834be5-e78a-4283-b355-b5feaffd0281.png)

**Comment by johnwalicki** [comment]
After:
![image](https://user-images.githubusercontent.com/17571232/219902637-9fe8be9c-f4bf-4f54-a95e-3cdd2361cba0.png)

**Comment by johnwalicki** [comment]
- https://open-horizon.github.io/docs/fdo/README-FDO1.1/
- https://open-horizon.github.io/docs/fdo/FDO-APIs/
